### ISSUE TITLE
SPA関連のバグ、気づいたこと

### ISSUE THREAD

**Issue by uminomae** [42trans/ft_transcendence#123]
- [x] Tournamentのplayでapp外れる #109  
- [x] 3D Pongが動かない
- [x] friendship Friend -> [Delete](https://localhost/app/user/info/user1/#)
- [x] base.htmlの中でbase.htmlが呼ばれる

**Comment by ak0327** [comment]
3D Pongが動かない件、vite再ビルトして`static/pong/three/`を更新してみてください
SPAに表示するため、three-jsに変更を加えています。ビルドしないとstatic/pong/threeに未反映であることが原因かもしれません。
