### ISSUE TITLE
index.jsのsetOnlineStatusはゲストの場合どうする？

### ISSUE THREAD

**Issue by uminomae** [42trans/ft_transcendence#146]
ゲストでSPA関連ページにアクセスすると401が出る。
165のfetchに対するハンドリングがされていると言えるのか不明
.thenで対応しているように見える。が、先にreturnが動いていて、そのエラーが出てる？よくわからない。

```


export function fetchUserId() {
    return fetch("/accounts/api/user/profile/")
        .then(response => {
            if (!response.ok) {
                console.log('GuestUser? UserID not found');
                return null;
            }
            return response.json();
        })
        .then(data => {
            if (!data.id) {
                console.log('GuestUser? UserID not found');
                return null;
            }
            return data.id;
        })
        .catch(error => {
            console.log('Error:', error);
            return null;
        });
}



```

**Comment by ak0327** [comment]
401のため、consoleで自動的にエラー判定されていそうですね
online状態取得のため、Login状態によらず`api/user/profile/`を叩き
返却値でGuest or Loginユーザーの判定をしていますが、
`api/user/profile/`が`IsAuthenticated`のためGuestには401が返却されています

401回避のため、`api/user/profile/`の認証を`AllowAny`にし、別ルートで判定した方が良さそうですね

**Comment by uminomae** [comment]
> 401のため、consoleで自動的にエラー判定されていそうですね
> 
> online状態取得のため、Login状態によらず`api/user/profile/`を叩き
> 
> 返却値でGuest or Loginユーザーの判定をしていますが、
> 
> `api/user/profile/`が`IsAuthenticated`のためGuestには401が返却されています
> 
> 
> 
> 401回避のため、`api/user/profile/`の認証を`AllowAny`にし、別ルートで判定した方が良さそうですね

fetchUserIdの呼び出し元の責任な気もします。APIも正当な実装でしょうし。
jsは呼び出し元でハンドリング可能なのでしょうが、開発サーバーで出てるエラーログへの影響がわからないので？？って感じです。包括的な対処方法があるのだろうか？と。

**Comment by uminomae** [comment]
dev server 8002にも出るのですね。consoleだけでなく。双方に包括的に対応する方法までは。endBtnのバグとってる最中に見つけただけなので深追いしてません。
<img width="328" alt="スクリーンショット 2024-06-05 11 15 24" src="https://github.com/42trans/ft_transcendence/assets/101631407/90b6fda7-8942-4ded-8d21-d6c5101879e2">
<img width="718" alt="スクリーンショット 2024-06-05 11 16 11" src="https://github.com/42trans/ft_transcendence/assets/101631407/27aef74d-477b-4d19-be60-5e49d2a83c11">
