### ISSUE TITLE
[fix?] DM: nickname変更の挙動

### ISSUE THREAD

**Issue by ak0327** [42trans/ft_transcendence#245]
nicknameを元にsender or notで振り分けているため、別windowでnicknameを変更すると正常に自分・相手の判別ができなくなる
user_idも渡せば分別できそうだが、余裕があれば...

<br>
user1のDM画面は開きっぱなし＆更新せず、DM相手test2がnicknameをTEST2に変更し、test2に戻した場合

![Screenshot 2024-06-16 at 15 39 26](https://github.com/42trans/ft_transcendence/assets/51146172/6b3b67d0-c782-41e7-865e-c21f836c3a97)

**Comment by uminomae** [comment]
> nicknameを元にsender or notで振り分けているため、別windowでnicknameを変更すると正常に自分・相手の判別ができなくなる user_idも渡せば分別できそうだが、余裕があれば...
> 
> 
> user1のDM画面は開きっぱなし＆更新せず、DM相手test2がnicknameをTEST2に変更し、test2に戻した場合
> ![Screenshot 2024-06-16 at 15 39 26](https://private-user-images.githubusercontent.com/51146172/340070054-6b3b67d0-c782-41e7-865e-c21f836c3a97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MjI3MzgsIm5iZiI6MTcxODUyMjQzOCwicGF0aCI6Ii81MTE0NjE3Mi8zNDAwNzAwNTQtNmIzYjY3ZDAtYzc4Mi00MWU3LTg2NWUtYzIxZjgzNmMzYTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDA3MjAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZDJmZThiZjM5ZDRhMTk0NzNjM2NhZjQ5MTZhZWM3ZmM0ZDRmZjQxMDMwMzk2M2Y3YmFlZTViYjNiMGYwNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gs7xgToVekS2wbdlfzV7lIt1wI0jMd0nFEEC8LKroC8)

トーナメントもそうですが、id識別で統一した方が良さそうですね。

spaは戻る進むに関する残り二つで、正常挙動は安定してます。かなりコーナーケースの類。一つは直せる見込みあり。
tryはmain()っぽい呼び出し元の関数だけ１ファイル？分やって、id識別に切り替える作業を優先しても良いかもですね。
