### ISSUE TITLE
tournamentはゲーム同様にcatchしたらリセット？　ページとゲームはちょっと扱いが違いそう。他のdmやログイン関連のhtmlと方針を合わせた方が良さそうな。

### ISSUE THREAD

**Issue by uminomae** [42trans/ft_transcendence#271]
chatかaccountのエラー処理方針と合わせた方が良い気がしたので。固くやるなら全部topにリセットして遷移が良さそうですが、あまり考えてないので、やりすぎて、ってことはあるかもしれません。重要なエラーや玉突きで起きそうなところがあればリセットしますが（ゲームに影響する箇所など）

**Comment by ak0327** [comment]
chat, accounts系のエラーは`console.error('hth: error: ${error}')`のみで、その後の処理ガン無視です
renderViewで開き直すか、switchPageでTOP遷移あたりを考えていましたが、
game同様、alert -> top遷移（windowリセット）に合わせましょうか？

**Comment by uminomae** [comment]
> chat, accounts系のエラーは`console.error('hth: error: ${error}')`のみで、その後の処理ガン無視です renderViewで開き直すか、switchPageでTOP遷移あたりを考えていましたが、 game同様、alert -> top遷移（windowリセット）に合わせましょうか？

影響がどの程度出るのかわからないので、ちょっとずつ重要そうな（よく出るエラーのとこ）ところで試して、それから判断したいです。やりすぎてもバグ出るから。

**Comment by uminomae** [comment]
呼び出し元でtry catch設定してるので、サブの方は大丈夫かな。
というムードだったんですが、
テキトーなとこで throw new Errorしてみら、あんまり良くない表示に。

よくわからない時は、
- try節は必ず呼び出し元に一つ。キャッチしてリセットするため
- そうしなくて良いことをテストしたらばしなくてもOK
の方が無難かもしれません。

<img width="1261" alt="スクリーンショット 2024-06-18 18 22 21" src="https://github.com/42trans/ft_transcendence/assets/101631407/a34c48c0-85cf-4df2-b2f6-b8a4d6122f3a">

**Comment by uminomae** [comment]
割と考えずに迷ったらリセットで良いのかもしれない。ハンドリング方針で考えること多い。
