### ISSUE TITLE
• 入力値検証: フォームやユーザー入力に対して、バックエンドがない場合はベースページ内で、バックエンドがある場合はサーバーサイドで、何らかの検証を実装する必要があります。

### ISSUE THREAD

**Issue by uminomae** [42trans/ft_transcendence#278]
- [x] `<form>`や` submit `で検索して、API側を一つずつチェック？
  - [x] tournament create #282

**Comment by ak0327** [comment]
これは全体的に目を通していますが、バックエンドの実装はできており、テストで検証済みです
フロント側で検証した方が早いケースもあり（フロント->バック->フロントの往復が必要なため）、フロント側で（重複していますが）検証しているケースも多いはずです

**Comment by uminomae** [comment]
`<form`で検索したところ、pong/は、validation不足のtournament新規作成の箇所だけ。それは先ほど修正済み。#282

<img width="354" alt="スクリーンショット 2024-06-19 6 58 34" src="https://github.com/42trans/ft_transcendence/assets/101631407/d4b636b4-3f5f-4262-b139-59cf7116c04a">
