### ISSUE TITLE
• パスワードのハッシュ化: データベースにパスワードを保存する場合、必ずハッシュ化してください。

### ISSUE THREAD

**Issue by uminomae** [42trans/ft_transcendence#279]
- [x] 意味がわかってないです。なんのことか調べるとこから系。hioikawa

**Comment by ak0327** [comment]
DBにはuserのパスワードがハッシュ化されて保存されています（djangoが自動的にハッシュ化しているはずです）

![Screenshot 2024-06-18 at 19 57 19](https://github.com/42trans/ft_transcendence/assets/51146172/3ddf8329-a340-475e-a8f2-de40e056dfb6)


各userのパスワードを平文で保存すると、管理者が見ることができたり、不正アクセスで流出する恐れがありますが、ハッシュ化すると（一般的に）複合が困難なので、元のパスワードが推測できず安全とされています。
パスワード照合の際は、入力されたパスワードをハッシュ化したものを照合し、成否判定するようになっていると思います
