### ISSUE TITLE
チャットで他のユーザーをPongゲームに招待できる  トーナメントシステムでは、次の対局が予想されるユーザーに警告できる

### ISSUE THREAD

**Issue by uminomae** [42trans/ft_transcendence#315]
実装方針：
## models Tournament
 - [x] round_is finished 追加：毎試合終了時に判定。値は0~2（このフラグを見てシステムが試合可能DM送る）
 - [x] メソッド: alert()：round_finishedを見て、次のラウンドが可能になったことを主催者にDM。システムから。

## DM
- [ ]「俺んちでPongしようぜ」ボタン

---
>  - ユーザーはチャットインターフェースを通じて他のユーザーをPongゲームで遊ぶために招待することができるようにする必要があります。
>  - トーナメントシステムは、次のゲームで予定されているユーザーに警告することができるようにする必要があります。
  
- ディフェンス用の説明を考える。
- 「俺んちでPongしようぜ」ボタンと「隣にいるけどリアルで言えないからDMするね。次はお前と当たる気がする！！」ボタンをfriendのとこに追加する
- トーナメント開催日時と場所が記述できれば親切

これをマージしたところからブランチを切りたい
https://github.com/42trans/ft_transcendence/pull/314

**Comment by uminomae** [comment]
やっつけ実装案
- リモートプレイは実装していない。したがって、オフライン対戦なので近くにいることが全て。
- nicknameを指定してボタンを押すと提携メッセージが送信される
<img width="1166" alt="スクリーンショット 2024-06-21 15 05 05" src="https://github.com/42trans/ft_transcendence/assets/101631407/5f477d0f-a645-4af2-9a63-ffb8c0f4cc7c">

**Comment by ak0327** [comment]
「隣にいるけどリアルで言えないからDMするね。」面白いですね🙃


リモートプレイ要件で、今回のスタンドアロンゲームの場合には納得できる機能として実装できない気がします
無理やり実装するならご提案いただいたように
登録済のfriendに「俺んちでPongしようぜ」招待メッセージを送るボタンの実装、くらいでしょうか
トーナメント内でloginしnicknameの存在が保証されているユーザーはorganizerのみなので、
次のゲームで予定されているユーザーへの警告は実装できないと思います（隣にいるので声かけて！！🫠）

**Comment by uminomae** [comment]
> * 次のゲームで予定されているユーザー
nickname以外にoptionでuseridも登録できるようにして、nickname宛に送るとuserのDMにいく。とかでしょかね。。

- ユーザー管理モジュールの「複数のトーナメント」と同じ論理展開で、リモートプレイ実装が前提の課題ではない。
- オフラインかオンラインかの記述はない。
- 我々はオフライン対戦のトーナメントを選択した。
- 次のゲームで予定されているユーザーは、ユーザー自身による目視確認で行われるので、次の対戦相手が誰かは特定できる。
- トーナメントシステムを用いてalertする内容は曖昧。

**Comment by uminomae** [comment]
> > * 次のゲームで予定されているユーザー
> 
> * ユーザー管理モジュールの「複数のトーナメント」と同じ論理展開で、リモートプレイ実装が前提の課題ではない。
> * オフラインかオンラインかの記述はない。
> * 我々はオフライン対戦のトーナメントを選択した。
> * 次のゲームで予定されているユーザーは、ユーザー自身による目視確認で行われるので、次の対戦相手が誰かは特定できる。
> * トーナメントシステムを用いてalertする内容は曖昧。
> * 結論：
>   
>   * nickname以外にoptionでuseridも登録できるようにして、nickname宛に送るとuserのDMにいく。
>   * とか、対戦可能になったらRoundのis_finishedで判定してDMをシステムから送る、とかでしょかね。。

アイディア

- models Tournament
  - round_is finished 追加：値は0~2（このフラグを見てシステムが試合可能DM送る）
  - player_id追加
    - 自己申告。迷惑メールの恐れがあるのは承知で許容
- API 
  - alert用：round_finishedを見て、次の試合に該当するuseridを返す
    - トリガーは試合結果受信時にメソッド呼び出す
- Chat
  - systemから試合可能DMを行う

**Comment by uminomae** [comment]
> > > * 次のゲームで予定されているユーザー
> > 
> > 
> > 
> > * ユーザー管理モジュールの「複数のトーナメント」と同じ論理展開で、リモートプレイ実装が前提の課題ではない。
> > * オフラインかオンラインかの記述はない。
> > * 我々はオフライン対戦のトーナメントを選択した。
> > * 次のゲームで予定されているユーザーは、ユーザー自身による目視確認で行われるので、次の対戦相手が誰かは特定できる。
> > * トーナメントシステムを用いてalertする内容は曖昧。
> > * 結論：
> >   
> >   * nickname以外にoptionでuseridも登録できるようにして、nickname宛に送るとuserのDMにいく。
> >   * とか、対戦可能になったらRoundのis_finishedで判定してDMをシステムから送る、とかでしょかね。。
> 
> アイディア
> 
> * models Tournament
>   
>   * round_is finished 追加：値は0~2（このフラグを見てシステムが試合可能DM送る）
>   * player_id追加
>     
>     * 自己申告。迷惑メールの恐れがあるのは承知で許容
> * API
>   
>   * alert用：round_finishedを見て、次の試合に該当するuseridを返す
>     
>     * トリガーは試合結果受信時にメソッド呼び出す
> * Chat
>   
>   * systemから試合可能DMを行う

ラウンド最終試合終了時、
フラグ見てシステムから主催者宛にDM。隣の人にも声かけて！と添えて。
これがもっとも簡単な実装でしょか。
オフライントーナメントは課題的に想定されてると思います。※ユーザー管理の複数トーナメントもオフライン許容してるように見える。

**Comment by uminomae** [comment]
動いたけど、再起動したら動かないDjango現象でハマり中
APIはテストでOKなのだけども。loggerが出てほしい。
<img width="869" alt="スクリーンショット 2024-06-22 4 17 09" src="https://github.com/42trans/ft_transcendence/assets/101631407/13d425a6-32c6-4b78-a975-b83320f7cf6c">

**Comment by uminomae** [comment]
修正完了

**Comment by uminomae** [comment]
毎試合 roundの全試合のis_finishedをloopで判定し、trueならsystemからDM送信
<img width="957" alt="スクリーンショット 2024-06-22 6 35 26" src="https://github.com/42trans/ft_transcendence/assets/101631407/2770c8e3-414f-4e11-b3c5-d2030dbf412b">
nicknameを指定して俺んチ来ないかボタンをクリックすると
<img width="957" alt="スクリーンショット 2024-06-22 6 35 48" src="https://github.com/42trans/ft_transcendence/assets/101631407/41ae916a-a2e8-496c-a1c3-8a6cd0039743">

お誘い文章が送信される
<img width="957" alt="スクリーンショット 2024-06-22 6 35 55" src="https://github.com/42trans/ft_transcendence/assets/101631407/b7a4a240-4786-466d-b6af-bbca2fffe402">
