### ISSUE TITLE
42login後のnavi更新

### ISSUE THREAD

**Issue by ak0327** [42trans/ft_transcendence#333]
firefoxで42login後、guest用のnaviが表示されている？
chromeはuser用に更新される

**Comment by uminomae** [comment]
> firefoxで42login後、guest用のnaviが表示されている？ chromeはuser用に更新される

今docker_rmから復帰して作業開始したのですが、DevでChromeもfifefoxもこれ出てました。

**Comment by uminomae** [comment]
> > firefoxで42login後、guest用のnaviが表示されている？ chromeはuser用に更新される
> 
> 今docker_rmから復帰して作業開始したのですが、DevでChromeもfifefoxもこれ出てました。

起動直後ってことでもなく、再現しますね。
いつも42でログインしてて、今気づいたので、本日15時以降のDevの更新じゃないかと思います。

**Comment by uminomae** [comment]
OKです

**Comment by ak0327** [comment]
毎回updateHeader()を呼び出すよう変更したため、ページ読み込みのオーバヘッドが大きくなりE2Eが落ちやすくなってる気がします🤕
