### ISSUE TITLE
[fix] 42signup nickname重複で500エラー

### ISSUE THREAD

**Issue by ak0327** [42trans/ft_transcendence#341]
42signupでintra nameがnicknameに登録（自動）
すでにnickname登録済みの時に500エラーになるため、要修正
適当なsuffixを付与する or nickname入力を求める方式にするなど

**Comment by uminomae** [comment]
> 42signupでintra nameがnicknameに登録（自動） すでにnickname登録済みの時に500エラーになるため、要修正 適当なsuffixを付与する or nickname入力を求める方式にするなど

適当にsuffixつけて、嫌なら変更して、という仕様でしょーがないのでは
